Aanpassingen na bieb sync
nl-design-system/themes pull request #542
Opened 2024-04-04 11:44 UTC by jeffreylauwers

2024-04-12 07:23 UTC, bddjong requested changes

2024-04-12 07:46 UTC, Robbert commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +        },
`line-height` kun je beïnvloeden door een paragraph in een form-field-error-message te gebruiken, ik raad aan om dat altijd zo te doen.

2024-04-12 07:46 UTC, Robbert commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +    "todo": {
@jeffreylauwers is font-weight nodig voor bepaalde themes, of kan die token weg?

2024-04-12 07:54 UTC, jeffreylauwers commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> -    "utrecht": {
Ok dan laat ik dit component op het 'Community' niveau.

2024-04-12 08:02 UTC, jeffreylauwers commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +    "todo": {
Kan weg. Zoals in de discussion voor Form field description is de zien is elke vorm tot nu toe 'regular'. Maar soms wel cursief. Dat lijkt me eigenlijk een no-go maargoed font-style zat er toch al niet bij.

https://github.com/orgs/nl-design-system/discussions/227

2024-04-12 08:04 UTC, jeffreylauwers commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +        },
Ok dan zou ik de tokens voor line-heigt kunnen verwijderen. Maar die van font-weight lijkt wel nodig. Er zijn meerdere organisaties die bold gebruiken voor de Form field error message.

https://github.com/orgs/nl-design-system/discussions/228

2024-04-12 08:24 UTC, Robbert commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +        },
@bddjong zou jij die font-weight token willen toevoegen aan de utrecht-form-field-error-message?

2024-04-12 08:44 UTC, bddjong commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +        },
https://github.com/nl-design-system/utrecht/pull/2194

2024-04-15 11:23 UTC, Robbert commented
These changes are part of #545 now

2024-04-15 11:23 UTC, closed without merging