Aligned textbox tokens with code.
nl-design-system/themes pull request #688
Opened 2024-09-03 09:36 UTC by jeffreylauwers

Renamed
- tokenset from `text input` to `textbox`.

Added token:
- `textbox.min-block-size`
- `textbox.invalid.border-block-end-width`

Removed token:
- `textbox.font-weight`

Prefix from `.utrecht` to `.todo`
- `textbox.focus.border-width`
- `textbox.hover.*`

2024-09-03 14:14 UTC, Robbert requested changes

2024-09-03 14:14 UTC, Robbert commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +          "$value": "auto"
```suggestion
          "$value": "{utrecht.textbox.border-width}"
```

2024-09-03 14:41 UTC, jeffreylauwers commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +          "$value": "auto"
Oh dit heb ik zojuist gedaan :)

2024-09-03 14:44 UTC, jeffreylauwers commented on packages/voorbeeld-design-tokens/figma/voorbeeld.tokens.json
> +            "$value": "auto"
En dit dan juist net even anders. Wat je hier voorstelt is beter. Dus ik ga hem zo doorvoeren.

2024-09-06 09:09 UTC, Robbert approved these changes

2024-09-06 09:13 UTC, merged